import { build as esbuild } from "esbuild";
import { build as viteBuild } from "vite";
import { rm, readFile, mkdir } from "fs/promises";

// server deps to bundle to reduce openat(2) syscalls
// which helps cold start times
const allowlist = [
  "@google/generative-ai",
  "axios",
  "connect-pg-simple",
  "cors",
  "date-fns",
  "drizzle-orm",
  "drizzle-zod",
  "express",
  "express-rate-limit",
  "express-session",
  "jsonwebtoken",
  "memorystore",
  "multer",
  "nanoid",
  "nodemailer",
  "openai",
  "passport",
  "passport-local",
  "pg",
  "stripe",
  "uuid",
  "ws",
  "xlsx",
  "zod",
  "zod-validation-error",
];

// ✅ Node ESM 런타임에서 createRequire / __filename / __dirname을 쓸 수 있도록
// dist 폴더에 "부트스트랩" 파일을 만들어서, 배포 실행 entry로 사용합니다.
// (배너 주입보다 훨씬 안전하고, ESM/CJS 혼종 문제를 피합니다.)
const SERVER_ENTRY = "server/index.ts";
const DIST_DIR = "dist";
const DIST_SERVER_BUNDLE = `${DIST_DIR}/index.js`;
const DIST_BOOTSTRAP = `${DIST_DIR}/start.mjs`;

function bootstrapCode() {
  // ESM 표준 방식으로 __filename/__dirname/createRequire 제공
  // 그리고 실제 번들(dist/index.js)을 import 해서 실행
  return `
// Auto-generated by script/build.ts
import { createRequire } from "module";
import { fileURLToPath } from "url";
import path from "path";

globalThis.require = createRequire(import.meta.url);
globalThis.__filename = fileURLToPath(import.meta.url);
globalThis.__dirname = path.dirname(globalThis.__filename);

// 실제 서버 번들 실행
await import("./index.js");
`.trimStart();
}

async function buildAll() {
  await rm(DIST_DIR, { recursive: true, force: true });
  await mkdir(DIST_DIR, { recursive: true });

  console.log("building client...");
  await viteBuild();

  console.log("building server...");
  const pkg = JSON.parse(await readFile("package.json", "utf-8"));
  const allDeps = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {}),
  ];

  // allowlist에 없는 것들은 external로 빼서 번들 크기/빌드 문제 줄이기
  const externals = allDeps.filter((dep) => !allowlist.includes(dep));

  await esbuild({
    entryPoints: [SERVER_ENTRY],
    platform: "node",
    bundle: true,

    // ✅ 핵심: 서버 번들을 ESM으로 깨끗하게 생성
    format: "esm",
    outfile: DIST_SERVER_BUNDLE,

    // ✅ 서버에서 동적으로 쓰는 경로 계산이 필요하면 코드에서 import.meta.url로 처리
    // (배너 주입 X)

    define: {
      "process.env.NODE_ENV": '"production"',
    },

    target: ["node20"],
    sourcemap: true,
    minify: true,
    external: externals,
    logLevel: "info",
  });

  // ✅ 배포/실행용 부트스트랩 생성 (ESM + 글로벌 호환)
  await rm(DIST_BOOTSTRAP, { force: true });
  await import("fs/promises").then(({ writeFile }) =>
    writeFile(DIST_BOOTSTRAP, bootstrapCode(), "utf-8"),
  );

  console.log(`✅ server bundle: ${DIST_SERVER_BUNDLE}`);
  console.log(`✅ bootstrap: ${DIST_BOOTSTRAP}`);
}

buildAll().catch((err) => {
  console.error(err);
  process.exit(1);
});
